# Instalação do R

         
Para este tutorial, nós iremos instalar dois softwares: R e RStudio. Para utilizar o RStudio, é necessário primeiro instalar o R.  
  
Assim, siga os passos para instalação de acordo com o sistema operacional de seu computador.   

## LINUX

### Instalar o R
- Passo 1: Abra o terminal. Se utilizar distribuição Fedora, pressione as teclas Super + T, e no Ubuntu Ctrl + Alt + t;  
- Passo 2: Com o terminal aberto digite a seguinte linha de comando:  
Fedora: `r sudo dnf install R`  
Ubuntu: `r sudo apt-get install r-base r-base-core`   
- Passo 3: Pressione a tecla Enter para confirmar;     
- Passo 4: Colocar a senha do usuário;   
- Passo 5: Confirmar. O R estará instalado e pode ser acessado.    
Link para eventual consulta: [http://cran-r.c3sl.ufpr.br/bin/linux/](http://cran-r.c3sl.ufpr.br/bin/linux/)

### Instalar o RStudio
Passo 1: Acesse o site [https://rstudio.com/products/rstudio/download/](https://rstudio.com/products/rstudio/download/)  
Passo 2: Encontre na página o local de download gratuito conforme figura abaixo:  
  

Passo 3: Encontre o sistema operacional do seu computador (Ubuntu, Fedora, Debian ou OpenSUSE) e faça download.  
Passo 4: Acesse o terminal na pasta onde foi feito o download e siga as instruções abaixo usando Fedora ou Ubuntu:  
Fedora: `r sudo dnf install nomedo_arquivo_baixado.rpm`  
Ex: `r sudo dnf install rstudio-1.3.959-x86_64.rpm`  
Ubuntu: `r sudo dpkg -i nomedo_arquivo_baixado.deb`  
Passo 5: Após isso, o RStudio estará instalado no seu computador e pronto para uso.  

## Mac OS X

### Instalar o R
- Passo 1: Abra o site [CRAN - https://cran.r-project.org/](https://cran.r-project.org/)    
- Passo 2: Clique em Download de R for (Mac) OS X.   
- Passo 3: Clique duas vezes no arquivo depois de baixado que será instalado no seu computador.   



### Instalar o RStudio
* Passo 1: Acesse o site [https://rstudio.com/products/rstudio/download/](https://rstudio.com/products/rstudio/download/)    
* Passo 2: Encontre na página o local de download gratuito conforme figura abaixo:  
  


* Passo 3: Encontre o sistema operacional do seu computador (Mac OS) e faça download.  
* Passo 4: Depois de baixado, clique duas vezes no arquivo para instalá-lo. Após, estará pronto para uso.  





## Windows  
### Instalar o R

* Passo 1: Clique no seguinte link [https://cran.r-project.org/bin/windows/base/]( https://cran.r-project.org/bin/windows/base/)   
* Passo 2: Clique em Download R for Windows (os números que aparecem nesse arquivo de download correspondem à versão do R disponível)   
  

* Passo 3: Clique duas vezes no arquivo depois de baixado, clique em avançar até finalizar a instalação que será instalado no seu computador.   

### Instalar o RStudio
* Passo 1: Acesse o site [https://rstudio.com/products/rstudio/download/](https://rstudio.com/products/rstudio/download/)  
* Passo 2: Encontre na página o local de download gratuito conforme figura abaixo:   

  

* Passo 3: Encontre o sistema operacional do seu computador (Windows) e faça download.  
* Passo 4: Depois de baixado, clique duas vezes no arquivo para instalá-lo. Após, estará pronto para uso.
